vich_uploader:
    db_driver: orm

    mappings:
        article_images:
            uri_prefix: '%app.path.article_images%'
            upload_destination: '%kernel.project_dir%/public/public%app.path.article_images%'
